name: "linux tests and documentation builds for 'kiara_plugin.core_types'"
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build conda package
      uses: prefix-dev/rattler-build-action@v0.2.6
      with:
        recipe-path: recipe/recipe.yaml
